# Configuration file of the application configuration server 

# Necessary to inform the eureka server registry, which the client is going to be registered with...  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/