# Configuration file of the application configuration server (This file holds common properties for all the microservices)

# Necessary to inform the eureka server registry, which the client is going to be registered with...  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  
# Actuator configuration  
management:
  endpoints:
    web:
      exposure:
        include: '*'